[v1]
"Xorfilter 0.0.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["Xorfilter"]
"cargo-audit 0.12.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-audit"]
"cargo-bump 1.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-bump"]
"cargo-deadlinks 0.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-deadlinks"]
"cargo-edit 0.3.0-alpha.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-add", "cargo-rm", "cargo-upgrade"]
"cargo-expand 1.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-expand"]
"cargo-fuzz 0.8.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-fuzz"]
"cargo-kcov 0.5.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-kcov"]
"cargo-make 0.32.7 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-make", "makers"]
"cargo-raze 0.7.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-raze"]
"cargo-travis 0.0.7 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-coverage", "cargo-coveralls"]
"cargo-watch 7.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-watch"]
"clippy 0.0.212 (git+https://github.com/rust-lang/rust-clippy/#a9f8d3a034b30d0a2bedfe99c107aeeefbf8e176)" = ["cargo-clippy", "clippy-driver"]
"evcxr_repl 0.3.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["evcxr"]
"exa 0.9.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["exa"]
"fd-find 8.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["fd"]
"git-absorb 0.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["git-absorb"]
"guessing_game 0.1.0 (path+file:///Users/hafiz/Desktop/Rust/guessing_game)" = ["guessing_game"]
"hyperfine 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["hyperfine"]
"mirai 1.0.5 (git+https://github.com/facebookexperimental/MIRAI#6bc8e908c15490c2fc8d50a8410ecbc3b1d4f18a)" = ["mirai"]
"racer 2.0.12 (registry+https://github.com/rust-lang/crates.io-index)" = ["racer"]
"rectangles 0.1.0 (path+file:///Users/hafiz/Desktop/Rust/rectangles)" = ["rectangles"]
"rustfmt 0.9.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-fmt", "rustfmt"]
"viu 0.1.1 (path+file:///Users/hafiz/Git/viu)" = ["viu"]
