[v1]
"cargo-edit 0.3.0-alpha.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-add", "cargo-rm", "cargo-upgrade"]
"cargo-kcov 0.5.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-kcov"]
"cargo-travis 0.0.7 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-coverage", "cargo-coveralls"]
"guessing_game 0.1.0 (path+file:///Users/hafiz/Desktop/Rust/guessing_game)" = ["guessing_game"]
"hyperfine 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["hyperfine"]
"racer 2.0.12 (registry+https://github.com/rust-lang/crates.io-index)" = ["racer"]
"rectangles 0.1.0 (path+file:///Users/hafiz/Desktop/Rust/rectangles)" = ["rectangles"]
"rustfmt 0.9.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-fmt", "rustfmt"]
